web:
  build: ./docker-compose/apache-php/
  links:
   - db
   - mailcatcher
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - .:/var/www/homecost
   - ./docker-compose/data/log/apache2:/var/log/apache2
db:
  image: feelpix/mysql-dev
  ports:
   - "3306:3306"
  volumes:
   - ./docker-compose/data/mysql:/var/lib/mysql
mailcatcher:
  image: feelpix/mailcatcher-dev
  ports:
   - "1080:1080"