TRUNCATE `rules`;
INSERT INTO `rules` (`rule`, `category_code`) VALUES('D.G.F.I.P. IMPOT|PRLV DIRECTION GENERALE DES FINA', 'IMPOTS');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('PRLV SEPA FILIA|PRLV SURAVENIR ASSURANCES', 'ASSURANCE');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('TELEREGLEMENT EDFPRO|EDFPRO TEPEDFPRO|EDF', 'EDF');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('ECHEANCE PRET|BNP Paribas Personal Finance|ECH PRET', 'CREDIT');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('COMMISSIONS COTISATION ESPRIT LIBRES|F COTISATION EUROCOMPTE', 'BANQUE');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('NETFLIX|PRLV Orange|MolotovTV 75', 'ABT');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('GEANT|LIDL|CHRONO 1023|SO.BIO|CARREFOUR MARKET', 'MIAM');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('PICARD SURGELES|PICARD SA|BIO C BON', 'MIAM');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('E.LECLERC STE EULALIE|E.LECLERC', 'MIAM');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('NESPRESSO', 'MIAM');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('ACT PERISC NET|ANSAMBLE-ELIOR|REGIE PESSAC', 'ECOLE');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('SOGEDO', 'EAU');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('VIR du Perso loyer', 'FRANCOIS');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('VIR de Perso Compte joint', 'LAURE');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('PRLV URSSAF RHONE ALPES - CNCESU', 'MENAGE');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('Spotify|ITUNES.COM', 'ABT');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('LDEF BORDEAUX|LDEF-BORDEAUX', 'EAU');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('AMAZON', 'AMAZON');
INSERT INTO `rules` (`rule`, `category_code`) VALUES('LEROY|CASTORAMA', 'BRICO');