INSERT INTO rules (rule, category_code) VALUES ('RETRAIT DAB', 'AUTRE');
INSERT INTO rules (rule, category_code) VALUES ('PRLV SEPA SFR FIXE ADSL', 'ABT');
INSERT INTO rules (rule, category_code) VALUES ('PRLV SEPA AUTOROUTES DU SUD DE LA FRANCE', 'VOITURE');
INSERT INTO rules (rule, category_code) VALUES ('D.G.F.I.P. IMPOT', 'IMPOTS');
INSERT INTO rules (rule, category_code) VALUES ('PRLV SEPA FILIA', 'ASS');
INSERT INTO rules (rule, category_code) VALUES ('TELEREGLEMENT EDFPRO|EDFPRO TEPEDFPRO', 'EDF');
INSERT INTO rules (rule, category_code) VALUES ('ECHEANCE PRET|BNP Paribas Personal Finance', 'CREDIT');
INSERT INTO rules (rule, category_code) VALUES ('COMMISSIONS COTISATION ESPRIT LIBRES', 'BANQUE');
INSERT INTO rules (rule, category_code) VALUES ('DECATHLON', 'LOOK');
INSERT INTO rules (rule, category_code) VALUES ('NETFLIX|PRLV Orange', 'ABT');
INSERT INTO rules (rule, category_code) VALUES ('GEANT|LIDL', 'MIAM');
INSERT INTO rules (rule, category_code) VALUES ('PICARD SURGELES', 'MIAM');
INSERT INTO rules (rule, category_code) VALUES ('WORLD OF WARCRA', 'ABT');
INSERT INTO rules (rule, category_code) VALUES ('E.LECLERC STE EULALIE|E.LECLERC COMMERCE ELECTRONIQUE', 'MIAM');
INSERT INTO rules (rule, category_code) VALUES ('PHARMACIE|MAISON SANTE PRO', 'DOC');
INSERT INTO rules (rule, category_code) VALUES ('STATION U CARNAC|DAC-INTERMARCHE|ESSO\\s', 'VOITURE');
INSERT INTO rules (rule, category_code) VALUES ('NESPRESSO', 'MIAM');
INSERT INTO rules (rule, category_code) VALUES ('CASTORAMA|BRICOMARCHE', 'BRICO');
INSERT INTO rules (rule, category_code) VALUES ('ACT PERISC NET', 'ECOLE');
INSERT INTO rules (rule, category_code) VALUES ('N HAIRJ PRO', 'LOOK');
INSERT INTO rules (rule, category_code) VALUES ('KIABI|LA HALLE', 'LOOK');
INSERT INTO rules (rule, category_code) VALUES ('SOGEDO', 'EAU');