INSERT INTO rules (rule, category_id) VALUES ('RETRAIT DAB', 9);
INSERT INTO rules (rule, category_id) VALUES ('PRLV SEPA SFR FIXE ADSL', 7);
INSERT INTO rules (rule, category_id) VALUES ('PRLV SEPA AUTOROUTES DU SUD DE LA FRANCE', 8);
INSERT INTO rules (rule, category_id) VALUES ('D.G.F.I.P. IMPOT', 6);
INSERT INTO rules (rule, category_id) VALUES ('PRLV SEPA FILIA', 7);
INSERT INTO rules (rule, category_id) VALUES ('TELEREGLEMENT EDFPRO|EDFPRO TEPEDFPRO', 10);
INSERT INTO rules (rule, category_id) VALUES ('ECHEANCE PRET|BNP Paribas Personal Finance', 11);
INSERT INTO rules (rule, category_id) VALUES ('COMMISSIONS COTISATION ESPRIT LIBRES', 5);
INSERT INTO rules (rule, category_id) VALUES ('DECATHLON', 3);
INSERT INTO rules (rule, category_id) VALUES ('NETFLIX', 5);
INSERT INTO rules (rule, category_id) VALUES ('GEANT|LIDL', 1);
INSERT INTO rules (rule, category_id) VALUES ('PICARD SURGELES', 1);
INSERT INTO rules (rule, category_id) VALUES ('WORLD OF WARCRA', 5);
INSERT INTO rules (rule, category_id) VALUES ('E.LECLERC STE EULALIE|E.LECLERC COMMERCE ELECTRONIQUE', 1);
INSERT INTO rules (rule, category_id) VALUES ('PHARMACIE|MAISON SANTE PRO', 4);
INSERT INTO rules (rule, category_id) VALUES ('STATION U CARNAC|DAC-INTERMARCHE|ESSO\\s', 2);
INSERT INTO rules (rule, category_id) VALUES ('NESPRESSO', 1);
INSERT INTO rules (rule, category_id) VALUES ('CASTORAMA|BRICOMARCHE', 7);
INSERT INTO rules (rule, category_id) VALUES ('ACT PERISC NET', 14);
INSERT INTO rules (rule, category_id) VALUES ('FY PETIT ST SAVIN', 10);
INSERT INTO rules (rule, category_id) VALUES ('N HAIRJ PRO', 12);
INSERT INTO rules (rule, category_id) VALUES ('KIABI|LA HALLE', 13);
INSERT INTO rules (rule, category_id) VALUES ('SOGEDO', 15);