TRUNCATE `category`;
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('CHARGE', 'Charges', 'Charges', 0);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('APPORT', 'Apports', 'Apports', 0);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('DIVERS', 'Divers', 'Divers', 0);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('MIAM', 'Nourritures', 'Miam', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('IMPOTS', 'Impôts', 'Impôts', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('EDF', 'Edf', 'Edf', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('EAU', 'Eau', 'Eau', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('CREDIT', 'Crédit', 'Crédit', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('ASSURANCE', 'Assurance', 'Assurance', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('BANQUE', 'Banque', 'Banque', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('ABT', 'Abonnement', 'Abonnement', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('ECOLE', 'Ecole', 'Ecole', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('MENAGE', 'Ménage', 'Ménage', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('FRANCOIS', 'François', 'François', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('LAURE', 'Laure', 'Laure', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('EXCEP', 'Exceptionnel', 'Excep', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('RALLONGE', 'Rallonge', 'Rallonge', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('AUTRE', 'Autre', 'Autre', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('LOISIR', 'Loisir', 'Loisir', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('AMAZON', 'Amazon', 'Amazon', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('RESTO', 'Restaurant', 'Resto', 1);
INSERT INTO `category` (`code`, `label`, `tag`, `show`) VALUES ('BRICO', 'Bricolage', 'Brico', 1);

TRUNCATE `subcategory`;
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'MIAM');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'IMPOTS');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'EDF');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'EAU');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'CREDIT');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'ASSURANCE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'BANQUE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'ABT');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'ECOLE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('CHARGE', 'MENAGE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('APPORT', 'FRANCOIS');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('APPORT', 'LAURE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('APPORT', 'EXCEP');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('APPORT', 'RALLONGE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('DIVERS', 'AUTRE');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('DIVERS', 'LOISIR');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('DIVERS', 'AMAZON');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('DIVERS', 'RESTO');
INSERT INTO `subcategory` (`code`, `category_code`) VALUES ('DIVERS', 'BRICO');