<?php
/**
 * Le but est de reconstruire les fichiers messages pour qu'il soit trié par clef
 * afin de faciliter la recherche ou l'ajout de clef de message
 * User: fschneider
 * Date: 15/01/14
 * Time: 17:31
 */

$reference = array(
    array('code' => '1','type' => '3','name' => 'benef','label' => 'users.level.benef'),
    array('code' => '1','type' => '5','name' => 'unregistered','label' => 'users.status.unregistered'),
    array('code' => '1','type' => '9','name' => 'brand','label' => 'mechanic.product.level.brand'),
    array('code' => '2','type' => '3','name' => 'conso','label' => 'users.level.conso'),
    array('code' => '2','type' => '5','name' => 'registered','label' => 'users.status.registered'),
    array('code' => '2','type' => '7','name' => 'acquiring','label' => 'point.status.acquiring'),
    array('code' => '2','type' => '9','name' => 'family','label' => 'mechanic.product.level.family'),
    array('code' => '3','type' => '3','name' => 'user','label' => 'users.level.user'),
    array('code' => '3','type' => '5','name' => 'blocked','label' => 'users.status.blocked'),
    array('code' => '3','type' => '7','name' => 'owned','label' => 'point.status.owned'),
    array('code' => '3','type' => '9','name' => 'product','label' => 'mechanic.product.level.product'),
    array('code' => '4','type' => '3','name' => 'suser','label' => 'users.level.suser'),
    array('code' => '4','type' => '7','name' => 'expendable','label' => 'point.status.expendable'),
    array('code' => '5','type' => '3','name' => 'dircom','label' => 'users.level.dircom'),
    array('code' => '5','type' => '7','name' => 'ranking','label' => 'point.status.ranking'),
    array('code' => '6','type' => '3','name' => 'admin','label' => 'users.level.admin'),
    array('code' => '7','type' => '3','name' => 'sadmin','label' => 'users.level.sadmin'),
    array('code' => '8','type' => '3','name' => 'dev','label' => 'users.level.dev'),
    array('code' => 'aa','type' => '1','name' => 'Afar','label' => 'lang.label.aa.aa'),
    array('code' => 'ab','type' => '1','name' => 'Abkhazian','label' => 'lang.label.ab.ab'),
    array('code' => 'AD','type' => '0','name' => 'Andorra','label' => 'Andorra'),
    array('code' => 'ADMIN','type' => '4','name' => 'ADMIN','label' => 'admin.administrators'),
    array('code' => 'ADP','type' => '2','name' => 'Andorran Peseta','label' => 'Andorran Peseta'),
    array('code' => 'AE','type' => '0','name' => 'United Arab Emirates','label' => 'United Arab Emirates'),
    array('code' => 'AED','type' => '2','name' => 'United Arab Emirates Dirham','label' => 'United Arab Emirates Dirham'),
    array('code' => 'AF','type' => '0','name' => 'Afghanistan','label' => 'Afghanistan'),
    array('code' => 'af','type' => '1','name' => 'Afrikaans','label' => 'lang.label.af.af'),
    array('code' => 'AFA','type' => '2','name' => 'Afghanistan Afghani','label' => 'Afghanistan Afghani'),
    array('code' => 'AG','type' => '0','name' => 'Antigua and/or Barbuda','label' => 'Antigua and/or Barbuda'),
    array('code' => 'AI','type' => '0','name' => 'Anguilla','label' => 'Anguilla'),
    array('code' => 'AL','type' => '0','name' => 'Albania','label' => 'Albania'),
    array('code' => 'ALL','type' => '2','name' => 'Albanian Lek','label' => 'Albanian Lek'),
    array('code' => 'AM','type' => '0','name' => 'Armenia','label' => 'Armenia'),
    array('code' => 'am','type' => '1','name' => 'Amharic','label' => 'lang.label.am.am'),
    array('code' => 'AMD','type' => '2','name' => 'Armenian Dram','label' => 'Armenian Dram'),
    array('code' => 'AN','type' => '0','name' => 'Netherlands Antilles','label' => 'Netherlands Antilles'),
    array('code' => 'ANG','type' => '2','name' => 'Netherlands Antillian Guilder','label' => 'Netherlands Antillian Guilder'),
    array('code' => 'AO','type' => '0','name' => 'Angola','label' => 'Angola'),
    array('code' => 'AOK','type' => '2','name' => 'Angolan Kwanza','label' => 'Angolan Kwanza'),
    array('code' => 'AQ','type' => '0','name' => 'Antarctica','label' => 'Antarctica'),
    array('code' => 'AR','type' => '0','name' => 'Argentina','label' => 'Argentina'),
    array('code' => 'ar','type' => '1','name' => 'Arabic','label' => 'lang.label.ar.ar'),
    array('code' => 'ARS','type' => '2','name' => 'Argentine Peso','label' => 'Argentine Peso'),
    array('code' => 'as','type' => '1','name' => 'Assamese','label' => 'lang.label.as.as'),
    array('code' => 'AT','type' => '0','name' => 'Austria','label' => 'Austria'),
    array('code' => 'AU','type' => '0','name' => 'Australia','label' => 'Australia'),
    array('code' => 'AUD','type' => '2','name' => 'Australian Dollar','label' => 'Australian Dollar'),
    array('code' => 'AW','type' => '0','name' => 'Aruba','label' => 'Aruba'),
    array('code' => 'AWG','type' => '2','name' => 'Aruban Florin','label' => 'Aruban Florin'),
    array('code' => 'ay','type' => '1','name' => 'Aymara','label' => 'lang.label.ay.ay'),
    array('code' => 'AZ','type' => '0','name' => 'Azerbaijan','label' => 'Azerbaijan'),
    array('code' => 'az','type' => '1','name' => 'Azerbaijani','label' => 'lang.label.az.az'),
    array('code' => 'BA','type' => '0','name' => 'Bosnia and Herzegovina','label' => 'Bosnia and Herzegovina'),
    array('code' => 'ba','type' => '1','name' => 'Bashkir','label' => 'lang.label.ba.ba'),
    array('code' => 'BB','type' => '0','name' => 'Barbados','label' => 'Barbados'),
    array('code' => 'BBD','type' => '2','name' => 'Barbados Dollar','label' => 'Barbados Dollar'),
    array('code' => 'BD','type' => '0','name' => 'Bangladesh','label' => 'Bangladesh'),
    array('code' => 'BDT','type' => '2','name' => 'Bangladeshi Taka','label' => 'Bangladeshi Taka'),
    array('code' => 'BE','type' => '0','name' => 'Belgium','label' => 'Belgium'),
    array('code' => 'be','type' => '1','name' => 'Byelorussian','label' => 'lang.label.be.be'),
    array('code' => 'BF','type' => '0','name' => 'Burkina Faso','label' => 'Burkina Faso'),
    array('code' => 'BG','type' => '0','name' => 'Bulgaria','label' => 'Bulgaria'),
    array('code' => 'bg','type' => '1','name' => 'Bulgarian','label' => 'lang.label.bg.bg'),
    array('code' => 'BGN','type' => '2','name' => 'Bulgarian Lev','label' => 'Bulgarian Lev'),
    array('code' => 'BH','type' => '0','name' => 'Bahrain','label' => 'Bahrain'),
    array('code' => 'bh','type' => '1','name' => 'Bihari','label' => 'lang.label.bh.bh'),
    array('code' => 'BHD','type' => '2','name' => 'Bahraini Dinar','label' => 'Bahraini Dinar'),
    array('code' => 'BI','type' => '0','name' => 'Burundi','label' => 'Burundi'),
    array('code' => 'bi','type' => '1','name' => 'Bislama','label' => 'lang.label.bi.bi'),
    array('code' => 'BIF','type' => '2','name' => 'Burundi Franc','label' => 'Burundi Franc'),
    array('code' => 'BJ','type' => '0','name' => 'Benin','label' => 'Benin'),
    array('code' => 'BM','type' => '0','name' => 'Bermuda','label' => 'Bermuda'),
    array('code' => 'BMD','type' => '2','name' => 'Bermudian Dollar','label' => 'Bermudian Dollar'),
    array('code' => 'BN','type' => '0','name' => 'Brunei Darussalam','label' => 'Brunei Darussalam'),
    array('code' => 'bn','type' => '1','name' => 'Bengali/Bangla','label' => 'lang.label.bn.bn'),
    array('code' => 'BND','type' => '2','name' => 'Brunei Dollar','label' => 'Brunei Dollar'),
    array('code' => 'BO','type' => '0','name' => 'Bolivia','label' => 'Bolivia'),
    array('code' => 'bo','type' => '1','name' => 'Tibetan','label' => 'lang.label.bo.bo'),
    array('code' => 'BOB','type' => '2','name' => 'Bolivian Boliviano','label' => 'Bolivian Boliviano'),
    array('code' => 'BR','type' => '0','name' => 'Brazil','label' => 'Brazil'),
    array('code' => 'br','type' => '1','name' => 'Breton','label' => 'lang.label.br.br'),
    array('code' => 'brand1','type' => '10','name' => 'brand1','label' => 'brand.brand1'),
    array('code' => 'brand2','type' => '10','name' => 'brand2','label' => 'brand.brand2'),
    array('code' => 'brand3','type' => '10','name' => 'brand3','label' => 'brand.brand3'),
    array('code' => 'BRL','type' => '2','name' => 'Brazilian Real','label' => 'Brazilian Real'),
    array('code' => 'BS','type' => '0','name' => 'Bahamas','label' => 'Bahamas'),
    array('code' => 'BSD','type' => '2','name' => 'Bahamian Dollar','label' => 'Bahamian Dollar'),
    array('code' => 'BT','type' => '0','name' => 'Bhutan','label' => 'Bhutan'),
    array('code' => 'BTN','type' => '2','name' => 'Bhutan Ngultrum','label' => 'Bhutan Ngultrum'),
    array('code' => 'BUK','type' => '2','name' => 'Burma Kyat','label' => 'Burma Kyat'),
    array('code' => 'BV','type' => '0','name' => 'Bouvet Island','label' => 'Bouvet Island'),
    array('code' => 'BW','type' => '0','name' => 'Botswana','label' => 'Botswana'),
    array('code' => 'BWP','type' => '2','name' => 'Botswanian Pula','label' => 'Botswanian Pula'),
    array('code' => 'BY','type' => '0','name' => 'Belarus','label' => 'Belarus'),
    array('code' => 'BZ','type' => '0','name' => 'Belize','label' => 'Belize'),
    array('code' => 'BZD','type' => '2','name' => 'Belize Dollar','label' => 'Belize Dollar'),
    array('code' => 'CA','type' => '0','name' => 'Canada','label' => 'Canada'),
    array('code' => 'ca','type' => '1','name' => 'Catalan','label' => 'lang.label.ca.ca'),
    array('code' => 'CAD','type' => '2','name' => 'Canadian Dollar','label' => 'Canadian Dollar'),
    array('code' => 'CC','type' => '0','name' => 'Cocos (Keeling) Islands','label' => 'Cocos (Keeling) Islands'),
    array('code' => 'CF','type' => '0','name' => 'Central African Republic','label' => 'Central African Republic'),
    array('code' => 'CG','type' => '0','name' => 'Congo','label' => 'Congo'),
    array('code' => 'CH','type' => '0','name' => 'Switzerland','label' => 'Switzerland'),
    array('code' => 'CHF','type' => '2','name' => 'Swiss Franc','label' => 'Swiss Franc'),
    array('code' => 'CI','type' => '0','name' => 'Ivory Coast','label' => 'Ivory Coast'),
    array('code' => 'CK','type' => '0','name' => 'Cook Islands','label' => 'Cook Islands'),
    array('code' => 'CL','type' => '0','name' => 'Chile','label' => 'Chile'),
    array('code' => 'CLF','type' => '2','name' => 'Chilean Unidades de Fomento','label' => 'Chilean Unidades de Fomento'),
    array('code' => 'CLP','type' => '2','name' => 'Chilean Peso','label' => 'Chilean Peso'),
    array('code' => 'CM','type' => '0','name' => 'Cameroon','label' => 'Cameroon'),
    array('code' => 'CN','type' => '0','name' => 'China','label' => 'China'),
    array('code' => 'CNY','type' => '2','name' => 'Yuan (Chinese) Renminbi','label' => 'Yuan (Chinese) Renminbi'),
    array('code' => 'CO','type' => '0','name' => 'Colombia','label' => 'Colombia'),
    array('code' => 'co','type' => '1','name' => 'Corsican','label' => 'lang.label.co.co'),
    array('code' => 'COP','type' => '2','name' => 'Colombian Peso','label' => 'Colombian Peso'),
    array('code' => 'CR','type' => '0','name' => 'Costa Rica','label' => 'Costa Rica'),
    array('code' => 'CRC','type' => '2','name' => 'Costa Rican Colon','label' => 'Costa Rican Colon'),
    array('code' => 'cs','type' => '1','name' => 'Czech','label' => 'lang.label.cs.cs'),
    array('code' => 'CU','type' => '0','name' => 'Cuba','label' => 'Cuba'),
    array('code' => 'CUP','type' => '2','name' => 'Cuban Peso','label' => 'Cuban Peso'),
    array('code' => 'CV','type' => '0','name' => 'Cape Verde','label' => 'Cape Verde'),
    array('code' => 'CVE','type' => '2','name' => 'Cape Verde Escudo','label' => 'Cape Verde Escudo'),
    array('code' => 'CX','type' => '0','name' => 'Christmas Island','label' => 'Christmas Island'),
    array('code' => 'CY','type' => '0','name' => 'Cyprus','label' => 'Cyprus'),
    array('code' => 'cy','type' => '1','name' => 'Welsh','label' => 'lang.label.cy.cy'),
    array('code' => 'CYP','type' => '2','name' => 'Cyprus Pound','label' => 'Cyprus Pound'),
    array('code' => 'CZ','type' => '0','name' => 'Czech Republic','label' => 'Czech Republic'),
    array('code' => 'CZK','type' => '2','name' => 'Czech Republic Koruna','label' => 'Czech Republic Koruna'),
    array('code' => 'da','type' => '1','name' => 'Danish','label' => 'lang.label.da.da'),
    array('code' => 'DE','type' => '0','name' => 'Germany','label' => 'Germany'),
    array('code' => 'de','type' => '1','name' => 'German','label' => 'lang.label.de.de'),
    array('code' => 'DJ','type' => '0','name' => 'Djibouti','label' => 'Djibouti'),
    array('code' => 'DK','type' => '0','name' => 'Denmark','label' => 'Denmark'),
    array('code' => 'DKK','type' => '2','name' => 'Danish Krone','label' => 'Danish Krone'),
    array('code' => 'DM','type' => '0','name' => 'Dominica','label' => 'Dominica'),
    array('code' => 'DO','type' => '0','name' => 'Dominican Republic','label' => 'Dominican Republic'),
    array('code' => 'DOP','type' => '2','name' => 'Dominican Peso','label' => 'Dominican Peso'),
    array('code' => 'DS','type' => '0','name' => 'American Samoa','label' => 'American Samoa'),
    array('code' => 'DZ','type' => '0','name' => 'Algeria','label' => 'Algeria'),
    array('code' => 'dz','type' => '1','name' => 'Bhutani','label' => 'lang.label.dz.dz'),
    array('code' => 'DZD','type' => '2','name' => 'Algerian Dinar','label' => 'Algerian Dinar'),
    array('code' => 'EC','type' => '0','name' => 'Ecuador','label' => 'Ecuador'),
    array('code' => 'ECS','type' => '2','name' => 'Ecuador Sucre','label' => 'Ecuador Sucre'),
    array('code' => 'EE','type' => '0','name' => 'Estonia','label' => 'Estonia'),
    array('code' => 'EEK','type' => '2','name' => 'Estonian Kroon (EEK)','label' => 'Estonian Kroon (EEK)'),
    array('code' => 'EG','type' => '0','name' => 'Egypt','label' => 'Egypt'),
    array('code' => 'EGP','type' => '2','name' => 'Egyptian Pound','label' => 'Egyptian Pound'),
    array('code' => 'EH','type' => '0','name' => 'Western Sahara','label' => 'Western Sahara'),
    array('code' => 'el','type' => '1','name' => 'Greek','label' => 'lang.label.el.el'),
    array('code' => 'en','type' => '1','name' => 'English','label' => 'lang.label.en.en'),
    array('code' => 'eo','type' => '1','name' => 'Esperanto','label' => 'lang.label.eo.eo'),
    array('code' => 'ER','type' => '0','name' => 'Eritrea','label' => 'Eritrea'),
    array('code' => 'ES','type' => '0','name' => 'Spain','label' => 'Spain'),
    array('code' => 'es','type' => '1','name' => 'Spanish','label' => 'lang.label.es.es'),
    array('code' => 'ET','type' => '0','name' => 'Ethiopia','label' => 'Ethiopia'),
    array('code' => 'et','type' => '1','name' => 'Estonian','label' => 'lang.label.et.et'),
    array('code' => 'ETB','type' => '2','name' => 'Ethiopian Birr','label' => 'Ethiopian Birr'),
    array('code' => 'eu','type' => '1','name' => 'Basque','label' => 'lang.label.eu.eu'),
    array('code' => 'EUR','type' => '2','name' => 'Euro','label' => 'Euro'),
    array('code' => 'EXTERNAL','type' => '4','name' => 'EXTERNAL','label' => 'admin.consumers.beneficiaries'),
    array('code' => 'fa','type' => '1','name' => 'Persian','label' => 'lang.label.fa.fa'),
    array('code' => 'FI','type' => '0','name' => 'Finland','label' => 'Finland'),
    array('code' => 'fi','type' => '1','name' => 'Finnish','label' => 'lang.label.fi.fi'),
    array('code' => 'FJ','type' => '0','name' => 'Fiji','label' => 'Fiji'),
    array('code' => 'fj','type' => '1','name' => 'Fiji','label' => 'lang.label.fj.fj'),
    array('code' => 'FJD','type' => '2','name' => 'Fiji Dollar','label' => 'Fiji Dollar'),
    array('code' => 'FK','type' => '0','name' => 'Falkland Islands (Malvinas)','label' => 'Falkland Islands (Malvinas)'),
    array('code' => 'FKP','type' => '2','name' => 'Falkland Islands Pound','label' => 'Falkland Islands Pound'),
    array('code' => 'FM','type' => '0','name' => 'Micronesia, Federated States of','label' => 'Micronesia, Federated States of'),
    array('code' => 'FO','type' => '0','name' => 'Faroe Islands','label' => 'Faroe Islands'),
    array('code' => 'fo','type' => '1','name' => 'Faeroese','label' => 'lang.label.fo.fo'),
    array('code' => 'FR','type' => '0','name' => 'France','label' => 'France'),
    array('code' => 'fr','type' => '1','name' => 'French','label' => 'lang.label.fr.fr'),
    array('code' => 'func1','type' => '12','name' => 'func1','label' => 'function.func1'),
    array('code' => 'func2','type' => '12','name' => 'func2','label' => 'function.func2'),
    array('code' => 'func3','type' => '12','name' => 'func3','label' => 'function.func3'),
    array('code' => 'fy','type' => '1','name' => 'Frisian','label' => 'lang.label.fy.fy'),
    array('code' => 'GA','type' => '0','name' => 'Gabon','label' => 'Gabon'),
    array('code' => 'ga','type' => '1','name' => 'Irish','label' => 'lang.label.ga.ga'),
    array('code' => 'GB','type' => '0','name' => 'United Kingdom','label' => 'United Kingdom'),
    array('code' => 'GBP','type' => '2','name' => 'British Pound','label' => 'British Pound'),
    array('code' => 'GD','type' => '0','name' => 'Grenada','label' => 'Grenada'),
    array('code' => 'gd','type' => '1','name' => 'Scots/Gaelic','label' => 'lang.label.gd.gd'),
    array('code' => 'GE','type' => '0','name' => 'Georgia','label' => 'Georgia'),
    array('code' => 'GF','type' => '0','name' => 'French Guiana','label' => 'French Guiana'),
    array('code' => 'GH','type' => '0','name' => 'Ghana','label' => 'Ghana'),
    array('code' => 'GHC','type' => '2','name' => 'Ghanaian Cedi','label' => 'Ghanaian Cedi'),
    array('code' => 'GI','type' => '0','name' => 'Gibraltar','label' => 'Gibraltar'),
    array('code' => 'GIP','type' => '2','name' => 'Gibraltar Pound','label' => 'Gibraltar Pound'),
    array('code' => 'GL','type' => '0','name' => 'Greenland','label' => 'Greenland'),
    array('code' => 'gl','type' => '1','name' => 'Galician','label' => 'lang.label.gl.gl'),
    array('code' => 'GM','type' => '0','name' => 'Gambia','label' => 'Gambia'),
    array('code' => 'GMD','type' => '2','name' => 'Gambian Dalasi','label' => 'Gambian Dalasi'),
    array('code' => 'GN','type' => '0','name' => 'Guinea','label' => 'Guinea'),
    array('code' => 'gn','type' => '1','name' => 'Guarani','label' => 'lang.label.gn.gn'),
    array('code' => 'GNF','type' => '2','name' => 'Guinea Franc','label' => 'Guinea Franc'),
    array('code' => 'GP','type' => '0','name' => 'Guadeloupe','label' => 'Guadeloupe'),
    array('code' => 'GQ','type' => '0','name' => 'Equatorial Guinea','label' => 'Equatorial Guinea'),
    array('code' => 'GR','type' => '0','name' => 'Greece','label' => 'Greece'),
    array('code' => 'GS','type' => '0','name' => 'South Georgia South Sandwich Islands','label' => 'South Georgia South Sandwich Islands'),
    array('code' => 'GT','type' => '0','name' => 'Guatemala','label' => 'Guatemala'),
    array('code' => 'GTQ','type' => '2','name' => 'Guatemalan Quetzal','label' => 'Guatemalan Quetzal'),
    array('code' => 'GU','type' => '0','name' => 'Guam','label' => 'Guam'),
    array('code' => 'gu','type' => '1','name' => 'Gujarati','label' => 'lang.label.gu.gu'),
    array('code' => 'GW','type' => '0','name' => 'Guinea-Bissau','label' => 'Guinea-Bissau'),
    array('code' => 'GWP','type' => '2','name' => 'Guinea-Bissau Peso','label' => 'Guinea-Bissau Peso'),
    array('code' => 'GY','type' => '0','name' => 'Guyana','label' => 'Guyana'),
    array('code' => 'GYD','type' => '2','name' => 'Guyanan Dollar','label' => 'Guyanan Dollar'),
    array('code' => 'ha','type' => '1','name' => 'Hausa','label' => 'lang.label.ha.ha'),
    array('code' => 'hi','type' => '1','name' => 'Hindi','label' => 'lang.label.hi.hi'),
    array('code' => 'HK','type' => '0','name' => 'Hong Kong','label' => 'Hong Kong'),
    array('code' => 'HKD','type' => '2','name' => 'Hong Kong Dollar','label' => 'Hong Kong Dollar'),
    array('code' => 'HM','type' => '0','name' => 'Heard and Mc Donald Islands','label' => 'Heard and Mc Donald Islands'),
    array('code' => 'HN','type' => '0','name' => 'Honduras','label' => 'Honduras'),
    array('code' => 'HNL','type' => '2','name' => 'Honduran Lempira','label' => 'Honduran Lempira'),
    array('code' => 'HR','type' => '0','name' => 'Croatia (Hrvatska)','label' => 'Croatia (Hrvatska)'),
    array('code' => 'hr','type' => '1','name' => 'Croatian','label' => 'lang.label.hr.hr'),
    array('code' => 'HT','type' => '0','name' => 'Haiti','label' => 'Haiti'),
    array('code' => 'HTG','type' => '2','name' => 'Haitian Gourde','label' => 'Haitian Gourde'),
    array('code' => 'HU','type' => '0','name' => 'Hungary','label' => 'Hungary'),
    array('code' => 'hu','type' => '1','name' => 'Hungarian','label' => 'lang.label.hu.hu'),
    array('code' => 'HUF','type' => '2','name' => 'Hungarian Forint','label' => 'Hungarian Forint'),
    array('code' => 'hy','type' => '1','name' => 'Armenian','label' => 'lang.label.hy.hy'),
    array('code' => 'ia','type' => '1','name' => 'Interlingua','label' => 'lang.label.ia.ia'),
    array('code' => 'ID','type' => '0','name' => 'Indonesia','label' => 'Indonesia'),
    array('code' => 'IDR','type' => '2','name' => 'Indonesian Rupiah','label' => 'Indonesian Rupiah'),
    array('code' => 'IE','type' => '0','name' => 'Ireland','label' => 'Ireland'),
    array('code' => 'ie','type' => '1','name' => 'Interlingue','label' => 'lang.label.ie.ie'),
    array('code' => 'IEP','type' => '2','name' => 'Irish Punt','label' => 'Irish Punt'),
    array('code' => 'ik','type' => '1','name' => 'Inupiak','label' => 'lang.label.ik.ik'),
    array('code' => 'IL','type' => '0','name' => 'Israel','label' => 'Israel'),
    array('code' => 'ILS','type' => '2','name' => 'Israeli Shekel','label' => 'Israeli Shekel'),
    array('code' => 'IN','type' => '0','name' => 'India','label' => 'India'),
    array('code' => 'in','type' => '1','name' => 'Indonesian','label' => 'lang.label.in.in'),
    array('code' => 'INR','type' => '2','name' => 'Indian Rupee','label' => 'Indian Rupee'),
    array('code' => 'INTERNAL','type' => '4','name' => 'INTERNAL','label' => 'admin.commercials.supervisors'),
    array('code' => 'IO','type' => '0','name' => 'British lndian Ocean Territory','label' => 'British lndian Ocean Territory'),
    array('code' => 'IQ','type' => '0','name' => 'Iraq','label' => 'Iraq'),
    array('code' => 'IQD','type' => '2','name' => 'Iraqi Dinar','label' => 'Iraqi Dinar'),
    array('code' => 'IR','type' => '0','name' => 'Iran (Islamic Republic of)','label' => 'Iran (Islamic Republic of)'),
    array('code' => 'IRR','type' => '2','name' => 'Iranian Rial','label' => 'Iranian Rial'),
    array('code' => 'IS','type' => '0','name' => 'Iceland','label' => 'Iceland'),
    array('code' => 'is','type' => '1','name' => 'Icelandic','label' => 'lang.label.is.is'),
    array('code' => 'IT','type' => '0','name' => 'Italy','label' => 'Italy'),
    array('code' => 'it','type' => '1','name' => 'Italian','label' => 'lang.label.it.it'),
    array('code' => 'iw','type' => '1','name' => 'Hebrew','label' => 'lang.label.iw.iw'),
    array('code' => 'ja','type' => '1','name' => 'Japanese','label' => 'lang.label.ja.ja'),
    array('code' => 'ji','type' => '1','name' => 'Yiddish','label' => 'lang.label.ji.ji'),
    array('code' => 'JM','type' => '0','name' => 'Jamaica','label' => 'Jamaica'),
    array('code' => 'JMD','type' => '2','name' => 'Jamaican Dollar','label' => 'Jamaican Dollar'),
    array('code' => 'JO','type' => '0','name' => 'Jordan','label' => 'Jordan'),
    array('code' => 'JOD','type' => '2','name' => 'Jordanian Dinar','label' => 'Jordanian Dinar'),
    array('code' => 'JP','type' => '0','name' => 'Japan','label' => 'Japan'),
    array('code' => 'JPY','type' => '2','name' => 'Japanese Yen','label' => 'Japanese Yen'),
    array('code' => 'jw','type' => '1','name' => 'Javanese','label' => 'lang.label.jw.jw'),
    array('code' => 'ka','type' => '1','name' => 'Georgian','label' => 'lang.label.ka.ka'),
    array('code' => 'KE','type' => '0','name' => 'Kenya','label' => 'Kenya'),
    array('code' => 'KES','type' => '2','name' => 'Kenyan Schilling','label' => 'Kenyan Schilling'),
    array('code' => 'KG','type' => '0','name' => 'Kyrgyzstan','label' => 'Kyrgyzstan'),
    array('code' => 'KH','type' => '0','name' => 'Cambodia','label' => 'Cambodia'),
    array('code' => 'KHR','type' => '2','name' => 'Kampuchean (Cambodian) Riel','label' => 'Kampuchean (Cambodian) Riel'),
    array('code' => 'KI','type' => '0','name' => 'Kiribati','label' => 'Kiribati'),
    array('code' => 'kk','type' => '1','name' => 'Kazakh','label' => 'lang.label.kk.kk'),
    array('code' => 'kl','type' => '1','name' => 'Greenlandic','label' => 'lang.label.kl.kl'),
    array('code' => 'KM','type' => '0','name' => 'Comoros','label' => 'Comoros'),
    array('code' => 'km','type' => '1','name' => 'Cambodian','label' => 'lang.label.km.km'),
    array('code' => 'KMF','type' => '2','name' => 'Comoros Franc','label' => 'Comoros Franc'),
    array('code' => 'KN','type' => '0','name' => 'Saint Kitts and Nevis','label' => 'Saint Kitts and Nevis'),
    array('code' => 'kn','type' => '1','name' => 'Kannada','label' => 'lang.label.kn.kn'),
    array('code' => 'ko','type' => '1','name' => 'Korean','label' => 'lang.label.ko.ko'),
    array('code' => 'KP','type' => '0','name' => 'Korea, Democratic People\'s Republic of','label' => 'Korea, Democratic People\'s Republic of'),
    array('code' => 'KPW','type' => '2','name' => 'North Korean Won','label' => 'North Korean Won'),
    array('code' => 'KR','type' => '0','name' => 'Korea, Republic of','label' => 'Korea, Republic of'),
    array('code' => 'KRW','type' => '2','name' => '(South) Korean Won','label' => '(South) Korean Won'),
    array('code' => 'ks','type' => '1','name' => 'Kashmiri','label' => 'lang.label.ks.ks'),
    array('code' => 'ku','type' => '1','name' => 'Kurdish','label' => 'lang.label.ku.ku'),
    array('code' => 'KW','type' => '0','name' => 'Kuwait','label' => 'Kuwait'),
    array('code' => 'KWD','type' => '2','name' => 'Kuwaiti Dinar','label' => 'Kuwaiti Dinar'),
    array('code' => 'KY','type' => '0','name' => 'Cayman Islands','label' => 'Cayman Islands'),
    array('code' => 'ky','type' => '1','name' => 'Kirghiz','label' => 'lang.label.ky.ky'),
    array('code' => 'KYD','type' => '2','name' => 'Cayman Islands Dollar','label' => 'Cayman Islands Dollar'),
    array('code' => 'KZ','type' => '0','name' => 'Kazakhstan','label' => 'Kazakhstan'),
    array('code' => 'LA','type' => '0','name' => 'Lao People\'s Democratic Republic','label' => 'Lao People\'s Democratic Republic'),
    array('code' => 'la','type' => '1','name' => 'Latin','label' => 'lang.label.la.la'),
    array('code' => 'LAK','type' => '2','name' => 'Lao Kip','label' => 'Lao Kip'),
    array('code' => 'LB','type' => '0','name' => 'Lebanon','label' => 'Lebanon'),
    array('code' => 'LBP','type' => '2','name' => 'Lebanese Pound','label' => 'Lebanese Pound'),
    array('code' => 'LC','type' => '0','name' => 'Saint Lucia','label' => 'Saint Lucia'),
    array('code' => 'LI','type' => '0','name' => 'Liechtenstein','label' => 'Liechtenstein'),
    array('code' => 'LK','type' => '0','name' => 'Sri Lanka','label' => 'Sri Lanka'),
    array('code' => 'LKR','type' => '2','name' => 'Sri Lanka Rupee','label' => 'Sri Lanka Rupee'),
    array('code' => 'ln','type' => '1','name' => 'Lingala','label' => 'lang.label.ln.ln'),
    array('code' => 'lo','type' => '1','name' => 'Laothian','label' => 'lang.label.lo.lo'),
    array('code' => 'LR','type' => '0','name' => 'Liberia','label' => 'Liberia'),
    array('code' => 'LRD','type' => '2','name' => 'Liberian Dollar','label' => 'Liberian Dollar'),
    array('code' => 'LS','type' => '0','name' => 'Lesotho','label' => 'Lesotho'),
    array('code' => 'LSL','type' => '2','name' => 'Lesotho Loti','label' => 'Lesotho Loti'),
    array('code' => 'LT','type' => '0','name' => 'Lithuania','label' => 'Lithuania'),
    array('code' => 'lt','type' => '1','name' => 'Lithuanian','label' => 'lang.label.lt.lt'),
    array('code' => 'LU','type' => '0','name' => 'Luxembourg','label' => 'Luxembourg'),
    array('code' => 'LV','type' => '0','name' => 'Latvia','label' => 'Latvia'),
    array('code' => 'lv','type' => '1','name' => 'Latvian/Lettish','label' => 'lang.label.lv.lv'),
    array('code' => 'LY','type' => '0','name' => 'Libyan Arab Jamahiriya','label' => 'Libyan Arab Jamahiriya'),
    array('code' => 'LYD','type' => '2','name' => 'Libyan Dinar','label' => 'Libyan Dinar'),
    array('code' => 'MA','type' => '0','name' => 'Morocco','label' => 'Morocco'),
    array('code' => 'MAD','type' => '2','name' => 'Moroccan Dirham','label' => 'Moroccan Dirham'),
    array('code' => 'madam','type' => '8','name' => 'users.civility.madam','label' => 'users.civility.madam'),
    array('code' => 'MC','type' => '0','name' => 'Monaco','label' => 'Monaco'),
    array('code' => 'MD','type' => '0','name' => 'Moldova, Republic of','label' => 'Moldova, Republic of'),
    array('code' => 'MECA','type' => '6','name' => 'meca','label' => 'point.type.meca'),
    array('code' => 'MG','type' => '0','name' => 'Madagascar','label' => 'Madagascar'),
    array('code' => 'mg','type' => '1','name' => 'Malagasy','label' => 'lang.label.mg.mg'),
    array('code' => 'MGF','type' => '2','name' => 'Malagasy Franc','label' => 'Malagasy Franc'),
    array('code' => 'MH','type' => '0','name' => 'Marshall Islands','label' => 'Marshall Islands'),
    array('code' => 'mi','type' => '1','name' => 'Maori','label' => 'lang.label.mi.mi'),
    array('code' => 'miss','type' => '8','name' => 'users.civility.miss','label' => 'users.civility.miss'),
    array('code' => 'mister','type' => '8','name' => 'users.civility.mister','label' => 'users.civility.mister'),
    array('code' => 'MK','type' => '0','name' => 'Macedonia','label' => 'Macedonia'),
    array('code' => 'mk','type' => '1','name' => 'Macedonian','label' => 'lang.label.mk.mk'),
    array('code' => 'ML','type' => '0','name' => 'Mali','label' => 'Mali'),
    array('code' => 'ml','type' => '1','name' => 'Malayalam','label' => 'lang.label.ml.ml'),
    array('code' => 'MM','type' => '0','name' => 'Myanmar','label' => 'Myanmar'),
    array('code' => 'MN','type' => '0','name' => 'Mongolia','label' => 'Mongolia'),
    array('code' => 'mn','type' => '1','name' => 'Mongolian','label' => 'lang.label.mn.mn'),
    array('code' => 'MNT','type' => '2','name' => 'Mongolian Tugrik','label' => 'Mongolian Tugrik'),
    array('code' => 'MO','type' => '0','name' => 'Macau','label' => 'Macau'),
    array('code' => 'mo','type' => '1','name' => 'Moldavian','label' => 'lang.label.mo.mo'),
    array('code' => 'MOP','type' => '2','name' => 'Macau Pataca','label' => 'Macau Pataca'),
    array('code' => 'MP','type' => '0','name' => 'Northern Mariana Islands','label' => 'Northern Mariana Islands'),
    array('code' => 'MQ','type' => '0','name' => 'Martinique','label' => 'Martinique'),
    array('code' => 'MR','type' => '0','name' => 'Mauritania','label' => 'Mauritania'),
    array('code' => 'mr','type' => '1','name' => 'Marathi','label' => 'lang.label.mr.mr'),
    array('code' => 'MRO','type' => '2','name' => 'Mauritanian Ouguiya','label' => 'Mauritanian Ouguiya'),
    array('code' => 'MS','type' => '0','name' => 'Montserrat','label' => 'Montserrat'),
    array('code' => 'ms','type' => '1','name' => 'Malay','label' => 'lang.label.ms.ms'),
    array('code' => 'MT','type' => '0','name' => 'Malta','label' => 'Malta'),
    array('code' => 'mt','type' => '1','name' => 'Maltese','label' => 'lang.label.mt.mt'),
    array('code' => 'MTL','type' => '2','name' => 'Maltese Lira','label' => 'Maltese Lira'),
    array('code' => 'MU','type' => '0','name' => 'Mauritius','label' => 'Mauritius'),
    array('code' => 'MUR','type' => '2','name' => 'Mauritius Rupee','label' => 'Mauritius Rupee'),
    array('code' => 'MV','type' => '0','name' => 'Maldives','label' => 'Maldives'),
    array('code' => 'MVR','type' => '2','name' => 'Maldive Rufiyaa','label' => 'Maldive Rufiyaa'),
    array('code' => 'MW','type' => '0','name' => 'Malawi','label' => 'Malawi'),
    array('code' => 'MWK','type' => '2','name' => 'Malawi Kwacha','label' => 'Malawi Kwacha'),
    array('code' => 'MX','type' => '0','name' => 'Mexico','label' => 'Mexico'),
    array('code' => 'MXP','type' => '2','name' => 'Mexican Peso','label' => 'Mexican Peso'),
    array('code' => 'MY','type' => '0','name' => 'Malaysia','label' => 'Malaysia'),
    array('code' => 'my','type' => '1','name' => 'Burmese','label' => 'lang.label.my.my'),
    array('code' => 'MYR','type' => '2','name' => 'Malaysian Ringgit','label' => 'Malaysian Ringgit'),
    array('code' => 'MZ','type' => '0','name' => 'Mozambique','label' => 'Mozambique'),
    array('code' => 'MZM','type' => '2','name' => 'Mozambique Metical','label' => 'Mozambique Metical'),
    array('code' => 'NA','type' => '0','name' => 'Namibia','label' => 'Namibia'),
    array('code' => 'na','type' => '1','name' => 'Nauru','label' => 'lang.label.na.na'),
    array('code' => 'NAD','type' => '2','name' => 'Namibian Dollar','label' => 'Namibian Dollar'),
    array('code' => 'NC','type' => '0','name' => 'New Caledonia','label' => 'New Caledonia'),
    array('code' => 'NE','type' => '0','name' => 'Niger','label' => 'Niger'),
    array('code' => 'ne','type' => '1','name' => 'Nepali','label' => 'lang.label.ne.ne'),
    array('code' => 'NF','type' => '0','name' => 'Norfork Island','label' => 'Norfork Island'),
    array('code' => 'NG','type' => '0','name' => 'Nigeria','label' => 'Nigeria'),
    array('code' => 'NGN','type' => '2','name' => 'Nigerian Naira','label' => 'Nigerian Naira'),
    array('code' => 'NI','type' => '0','name' => 'Nicaragua','label' => 'Nicaragua'),
    array('code' => 'NIO','type' => '2','name' => 'Nicaraguan Cordoba','label' => 'Nicaraguan Cordoba'),
    array('code' => 'NL','type' => '0','name' => 'Netherlands','label' => 'Netherlands'),
    array('code' => 'nl','type' => '1','name' => 'Dutch','label' => 'lang.label.nl.nl'),
    array('code' => 'NO','type' => '0','name' => 'Norway','label' => 'Norway'),
    array('code' => 'no','type' => '1','name' => 'Norwegian','label' => 'lang.label.no.no'),
    array('code' => 'NOK','type' => '2','name' => 'Norwegian Kroner','label' => 'Norwegian Kroner'),
    array('code' => 'NP','type' => '0','name' => 'Nepal','label' => 'Nepal'),
    array('code' => 'NPR','type' => '2','name' => 'Nepalese Rupee','label' => 'Nepalese Rupee'),
    array('code' => 'NR','type' => '0','name' => 'Nauru','label' => 'Nauru'),
    array('code' => 'NU','type' => '0','name' => 'Niue','label' => 'Niue'),
    array('code' => 'NZ','type' => '0','name' => 'New Zealand','label' => 'New Zealand'),
    array('code' => 'NZD','type' => '2','name' => 'New Zealand Dollar','label' => 'New Zealand Dollar'),
    array('code' => 'oc','type' => '1','name' => 'Occitan','label' => 'lang.label.oc.oc'),
    array('code' => 'OM','type' => '0','name' => 'Oman','label' => 'Oman'),
    array('code' => 'om','type' => '1','name' => 'Afan/Oromoor/Oriya','label' => 'lang.label.om.om'),
    array('code' => 'OMR','type' => '2','name' => 'Omani Rial','label' => 'Omani Rial'),
    array('code' => 'ORDER','type' => '6','name' => 'order','label' => 'point.type.order'),
    array('code' => 'PA','type' => '0','name' => 'Panama','label' => 'Panama'),
    array('code' => 'pa','type' => '1','name' => 'Punjabi','label' => 'lang.label.pa.pa'),
    array('code' => 'PAB','type' => '2','name' => 'Panamanian Balboa','label' => 'Panamanian Balboa'),
    array('code' => 'PE','type' => '0','name' => 'Peru','label' => 'Peru'),
    array('code' => 'PEN','type' => '2','name' => 'Peruvian Nuevo Sol','label' => 'Peruvian Nuevo Sol'),
    array('code' => 'PF','type' => '0','name' => 'French Polynesia','label' => 'French Polynesia'),
    array('code' => 'PG','type' => '0','name' => 'Papua New Guinea','label' => 'Papua New Guinea'),
    array('code' => 'PGK','type' => '2','name' => 'Papua New Guinea Kina','label' => 'Papua New Guinea Kina'),
    array('code' => 'PH','type' => '0','name' => 'Philippines','label' => 'Philippines'),
    array('code' => 'PHP','type' => '2','name' => 'Philippine Peso','label' => 'Philippine Peso'),
    array('code' => 'PK','type' => '0','name' => 'Pakistan','label' => 'Pakistan'),
    array('code' => 'PKR','type' => '2','name' => 'Pakistan Rupee','label' => 'Pakistan Rupee'),
    array('code' => 'PL','type' => '0','name' => 'Poland','label' => 'Poland'),
    array('code' => 'pl','type' => '1','name' => 'Polish','label' => 'lang.label.pl.pl'),
    array('code' => 'PLN','type' => '2','name' => 'Polish Zloty','label' => 'Polish Zloty'),
    array('code' => 'PM','type' => '0','name' => 'St. Pierre and Miquelon','label' => 'St. Pierre and Miquelon'),
    array('code' => 'PN','type' => '0','name' => 'Pitcairn','label' => 'Pitcairn'),
    array('code' => 'PR','type' => '0','name' => 'Puerto Rico','label' => 'Puerto Rico'),
    array('code' => 'ps','type' => '1','name' => 'Pashto/Pushto','label' => 'lang.label.ps.ps'),
    array('code' => 'PT','type' => '0','name' => 'Portugal','label' => 'Portugal'),
    array('code' => 'pt','type' => '1','name' => 'Portuguese','label' => 'lang.label.pt.pt'),
    array('code' => 'PURCHASE','type' => '6','name' => 'purchase','label' => 'point.type.purchase'),
    array('code' => 'PW','type' => '0','name' => 'Palau','label' => 'Palau'),
    array('code' => 'PY','type' => '0','name' => 'Paraguay','label' => 'Paraguay'),
    array('code' => 'PYG','type' => '2','name' => 'Paraguay Guarani','label' => 'Paraguay Guarani'),
    array('code' => 'QA','type' => '0','name' => 'Qatar','label' => 'Qatar'),
    array('code' => 'QAR','type' => '2','name' => 'Qatari Rial','label' => 'Qatari Rial'),
    array('code' => 'qu','type' => '1','name' => 'Quechua','label' => 'lang.label.qu.qu'),
    array('code' => 'RE','type' => '0','name' => 'Reunion','label' => 'Reunion'),
    array('code' => 'REGUL','type' => '6','name' => 'regul','label' => 'point.type.regul'),
    array('code' => 'rm','type' => '1','name' => 'Rhaeto-Romance','label' => 'lang.label.rm.rm'),
    array('code' => 'rn','type' => '1','name' => 'Kirundi','label' => 'lang.label.rn.rn'),
    array('code' => 'RO','type' => '0','name' => 'Romania','label' => 'Romania'),
    array('code' => 'ro','type' => '1','name' => 'Romanian','label' => 'lang.label.ro.ro'),
    array('code' => 'RON','type' => '2','name' => 'Romanian Leu','label' => 'Romanian Leu'),
    array('code' => 'RU','type' => '0','name' => 'Russian Federation','label' => 'Russian Federation'),
    array('code' => 'ru','type' => '1','name' => 'Russian','label' => 'lang.label.ru.ru'),
    array('code' => 'RUB','type' => '2','name' => 'Russian Ruble','label' => 'Russian Ruble'),
    array('code' => 'RW','type' => '0','name' => 'Rwanda','label' => 'Rwanda'),
    array('code' => 'rw','type' => '1','name' => 'Kinyarwanda','label' => 'lang.label.rw.rw'),
    array('code' => 'RWF','type' => '2','name' => 'Rwanda Franc','label' => 'Rwanda Franc'),
    array('code' => 'SA','type' => '0','name' => 'Saudi Arabia','label' => 'Saudi Arabia'),
    array('code' => 'sa','type' => '1','name' => 'Sanskrit','label' => 'lang.label.sa.sa'),
    array('code' => 'SAR','type' => '2','name' => 'Saudi Arabian Riyal','label' => 'Saudi Arabian Riyal'),
    array('code' => 'SB','type' => '0','name' => 'Solomon Islands','label' => 'Solomon Islands'),
    array('code' => 'SBD','type' => '2','name' => 'Solomon Islands Dollar','label' => 'Solomon Islands Dollar'),
    array('code' => 'SC','type' => '0','name' => 'Seychelles','label' => 'Seychelles'),
    array('code' => 'SCR','type' => '2','name' => 'Seychelles Rupee','label' => 'Seychelles Rupee'),
    array('code' => 'SD','type' => '0','name' => 'Sudan','label' => 'Sudan'),
    array('code' => 'sd','type' => '1','name' => 'Sindhi','label' => 'lang.label.sd.sd'),
    array('code' => 'SDP','type' => '2','name' => 'Sudanese Pound','label' => 'Sudanese Pound'),
    array('code' => 'SE','type' => '0','name' => 'Sweden','label' => 'Sweden'),
    array('code' => 'SEK','type' => '2','name' => 'Swedish Krona','label' => 'Swedish Krona'),
    array('code' => 'SG','type' => '0','name' => 'Singapore','label' => 'Singapore'),
    array('code' => 'sg','type' => '1','name' => 'Sangro','label' => 'lang.label.sg.sg'),
    array('code' => 'SGD','type' => '2','name' => 'Singapore Dollar','label' => 'Singapore Dollar'),
    array('code' => 'SH','type' => '0','name' => 'St. Helena','label' => 'St. Helena'),
    array('code' => 'sh','type' => '1','name' => 'Serbo-Croatian','label' => 'lang.label.sh.sh'),
    array('code' => 'SHP','type' => '2','name' => 'St. Helena Pound','label' => 'St. Helena Pound'),
    array('code' => 'SI','type' => '0','name' => 'Slovenia','label' => 'Slovenia'),
    array('code' => 'si','type' => '1','name' => 'Singhalese','label' => 'lang.label.si.si'),
    array('code' => 'SJ','type' => '0','name' => 'Svalbarn and Jan Mayen Islands','label' => 'Svalbarn and Jan Mayen Islands'),
    array('code' => 'SK','type' => '0','name' => 'Slovakia','label' => 'Slovakia'),
    array('code' => 'sk','type' => '1','name' => 'Slovak','label' => 'lang.label.sk.sk'),
    array('code' => 'SKK','type' => '2','name' => 'Slovak Koruna','label' => 'Slovak Koruna'),
    array('code' => 'SL','type' => '0','name' => 'Sierra Leone','label' => 'Sierra Leone'),
    array('code' => 'sl','type' => '1','name' => 'Slovenian','label' => 'lang.label.sl.sl'),
    array('code' => 'SLL','type' => '2','name' => 'Sierra Leone Leone','label' => 'Sierra Leone Leone'),
    array('code' => 'SM','type' => '0','name' => 'San Marino','label' => 'San Marino'),
    array('code' => 'sm','type' => '1','name' => 'Samoan','label' => 'lang.label.sm.sm'),
    array('code' => 'SN','type' => '0','name' => 'Senegal','label' => 'Senegal'),
    array('code' => 'sn','type' => '1','name' => 'Shona','label' => 'lang.label.sn.sn'),
    array('code' => 'SO','type' => '0','name' => 'Somalia','label' => 'Somalia'),
    array('code' => 'so','type' => '1','name' => 'Somali','label' => 'lang.label.so.so'),
    array('code' => 'SOS','type' => '2','name' => 'Somali Schilling','label' => 'Somali Schilling'),
    array('code' => 'sq','type' => '1','name' => 'Albanian','label' => 'lang.label.sq.sq'),
    array('code' => 'SR','type' => '0','name' => 'Suriname','label' => 'Suriname'),
    array('code' => 'sr','type' => '1','name' => 'Serbian','label' => 'lang.label.sr.sr'),
    array('code' => 'SRG','type' => '2','name' => 'Suriname Guilder','label' => 'Suriname Guilder'),
    array('code' => 'ss','type' => '1','name' => 'Siswati','label' => 'lang.label.ss.ss'),
    array('code' => 'ST','type' => '0','name' => 'Sao Tome and Principe','label' => 'Sao Tome and Principe'),
    array('code' => 'st','type' => '1','name' => 'Sesotho','label' => 'lang.label.st.st'),
    array('code' => 'STD','type' => '2','name' => 'Sao Tome and Principe Dobra','label' => 'Sao Tome and Principe Dobra'),
    array('code' => 'su','type' => '1','name' => 'Sundanese','label' => 'lang.label.su.su'),
    array('code' => 'SV','type' => '0','name' => 'El Salvador','label' => 'El Salvador'),
    array('code' => 'sv','type' => '1','name' => 'Swedish','label' => 'lang.label.sv.sv'),
    array('code' => 'SVC','type' => '2','name' => 'El Salvador Colon','label' => 'El Salvador Colon'),
    array('code' => 'sw','type' => '1','name' => 'Swahili','label' => 'lang.label.sw.sw'),
    array('code' => 'SY','type' => '0','name' => 'Syrian Arab Republic','label' => 'Syrian Arab Republic'),
    array('code' => 'SYP','type' => '2','name' => 'Syrian Potmd','label' => 'Syrian Potmd'),
    array('code' => 'SZ','type' => '0','name' => 'Swaziland','label' => 'Swaziland'),
    array('code' => 'SZL','type' => '2','name' => 'Swaziland Lilangeni','label' => 'Swaziland Lilangeni'),
    array('code' => 'ta','type' => '1','name' => 'Tamil','label' => 'lang.label.ta.ta'),
    array('code' => 'TC','type' => '0','name' => 'Turks and Caicos Islands','label' => 'Turks and Caicos Islands'),
    array('code' => 'TD','type' => '0','name' => 'Chad','label' => 'Chad'),
    array('code' => 'te','type' => '1','name' => 'Tegulu','label' => 'lang.label.te.te'),
    array('code' => 'TF','type' => '0','name' => 'French Southern Territories','label' => 'French Southern Territories'),
    array('code' => 'TG','type' => '0','name' => 'Togo','label' => 'Togo'),
    array('code' => 'tg','type' => '1','name' => 'Tajik','label' => 'lang.label.tg.tg'),
    array('code' => 'TH','type' => '0','name' => 'Thailand','label' => 'Thailand'),
    array('code' => 'th','type' => '1','name' => 'Thai','label' => 'lang.label.th.th'),
    array('code' => 'THB','type' => '2','name' => 'Thai Baht','label' => 'Thai Baht'),
    array('code' => 'ti','type' => '1','name' => 'Tigrinya','label' => 'lang.label.ti.ti'),
    array('code' => 'TJ','type' => '0','name' => 'Tajikistan','label' => 'Tajikistan'),
    array('code' => 'TK','type' => '0','name' => 'Tokelau','label' => 'Tokelau'),
    array('code' => 'tk','type' => '1','name' => 'Turkmen','label' => 'lang.label.tk.tk'),
    array('code' => 'tl','type' => '1','name' => 'Tagalog','label' => 'lang.label.tl.tl'),
    array('code' => 'TM','type' => '0','name' => 'Turkmenistan','label' => 'Turkmenistan'),
    array('code' => 'TN','type' => '0','name' => 'Tunisia','label' => 'Tunisia'),
    array('code' => 'tn','type' => '1','name' => 'Setswana','label' => 'lang.label.tn.tn'),
    array('code' => 'TND','type' => '2','name' => 'Tunisian Dinar','label' => 'Tunisian Dinar'),
    array('code' => 'TO','type' => '0','name' => 'Tonga','label' => 'Tonga'),
    array('code' => 'to','type' => '1','name' => 'Tonga','label' => 'lang.label.to.to'),
    array('code' => 'TOP','type' => '2','name' => 'Tongan Paanga','label' => 'Tongan Paanga'),
    array('code' => 'TP','type' => '0','name' => 'East Timor','label' => 'East Timor'),
    array('code' => 'TPE','type' => '2','name' => 'East Timor Escudo','label' => 'East Timor Escudo'),
    array('code' => 'TR','type' => '0','name' => 'Turkey','label' => 'Turkey'),
    array('code' => 'tr','type' => '1','name' => 'Turkish','label' => 'lang.label.tr.tr'),
    array('code' => 'TRY','type' => '2','name' => 'Turkish Lira','label' => 'Turkish Lira'),
    array('code' => 'ts','type' => '1','name' => 'Tsonga','label' => 'lang.label.ts.ts'),
    array('code' => 'TT','type' => '0','name' => 'Trinidad and Tobago','label' => 'Trinidad and Tobago'),
    array('code' => 'tt','type' => '1','name' => 'Tatar','label' => 'lang.label.tt.tt'),
    array('code' => 'TTD','type' => '2','name' => 'Trinidad and Tobago Dollar','label' => 'Trinidad and Tobago Dollar'),
    array('code' => 'TV','type' => '0','name' => 'Tuvalu','label' => 'Tuvalu'),
    array('code' => 'TW','type' => '0','name' => 'Taiwan','label' => 'Taiwan'),
    array('code' => 'tw','type' => '1','name' => 'Twi','label' => 'lang.label.tw.tw'),
    array('code' => 'TWD','type' => '2','name' => 'Taiwan Dollar','label' => 'Taiwan Dollar'),
    array('code' => 'TY','type' => '0','name' => 'Mayotte','label' => 'Mayotte'),
    array('code' => 'typo1','type' => '11','name' => 'typo1','label' => 'typology.typo1'),
    array('code' => 'typo2','type' => '11','name' => 'typo2','label' => 'typology.typo2'),
    array('code' => 'typo3','type' => '11','name' => 'typo3','label' => 'typology.typo3'),
    array('code' => 'TZ','type' => '0','name' => 'Tanzania, United Republic of','label' => 'Tanzania, United Republic of'),
    array('code' => 'TZS','type' => '2','name' => 'Tanzanian Schilling','label' => 'Tanzanian Schilling'),
    array('code' => 'UA','type' => '0','name' => 'Ukraine','label' => 'Ukraine'),
    array('code' => 'UG','type' => '0','name' => 'Uganda','label' => 'Uganda'),
    array('code' => 'UGX','type' => '2','name' => 'Uganda Shilling','label' => 'Uganda Shilling'),
    array('code' => 'uk','type' => '1','name' => 'Ukrainian','label' => 'lang.label.uk.uk'),
    array('code' => 'UM','type' => '0','name' => 'United States minor outlying islands','label' => 'United States minor outlying islands'),
    array('code' => 'ur','type' => '1','name' => 'Urdu','label' => 'lang.label.ur.ur'),
    array('code' => 'US','type' => '0','name' => 'United States','label' => 'United States'),
    array('code' => 'USD','type' => '2','name' => 'US Dollar','label' => 'US Dollar'),
    array('code' => 'UY','type' => '0','name' => 'Uruguay','label' => 'Uruguay'),
    array('code' => 'UYU','type' => '2','name' => 'Uruguayan Peso','label' => 'Uruguayan Peso'),
    array('code' => 'UZ','type' => '0','name' => 'Uzbekistan','label' => 'Uzbekistan'),
    array('code' => 'uz','type' => '1','name' => 'Uzbek','label' => 'lang.label.uz.uz'),
    array('code' => 'VA','type' => '0','name' => 'Vatican City State','label' => 'Vatican City State'),
    array('code' => 'VC','type' => '0','name' => 'Saint Vincent and the Grenadines','label' => 'Saint Vincent and the Grenadines'),
    array('code' => 'VE','type' => '0','name' => 'Venezuela','label' => 'Venezuela'),
    array('code' => 'VEF','type' => '2','name' => 'Venezualan Bolivar','label' => 'Venezualan Bolivar'),
    array('code' => 'VG','type' => '0','name' => 'Virigan Islands (British)','label' => 'Virigan Islands (British)'),
    array('code' => 'VI','type' => '0','name' => 'Virgin Islands (U.S.)','label' => 'Virgin Islands (U.S.)'),
    array('code' => 'vi','type' => '1','name' => 'Vietnamese','label' => 'lang.label.vi.vi'),
    array('code' => 'VN','type' => '0','name' => 'Vietnam','label' => 'Vietnam'),
    array('code' => 'VND','type' => '2','name' => 'Vietnamese Dong','label' => 'Vietnamese Dong'),
    array('code' => 'vo','type' => '1','name' => 'Volapuk','label' => 'lang.label.vo.vo'),
    array('code' => 'VU','type' => '0','name' => 'Vanuatu','label' => 'Vanuatu'),
    array('code' => 'VUV','type' => '2','name' => 'Vanuatu Vatu','label' => 'Vanuatu Vatu'),
    array('code' => 'WF','type' => '0','name' => 'Wallis and Futuna Islands','label' => 'Wallis and Futuna Islands'),
    array('code' => 'wo','type' => '1','name' => 'Wolof','label' => 'lang.label.wo.wo'),
    array('code' => 'WS','type' => '0','name' => 'Samoa','label' => 'Samoa'),
    array('code' => 'WST','type' => '2','name' => 'Samoan Tala','label' => 'Samoan Tala'),
    array('code' => 'XAF','type' => '2','name' => 'Communauté Financière Africaine BEAC, Francs','label' => 'Communauté Financière Africaine BEAC, Francs'),
    array('code' => 'XAG','type' => '2','name' => 'Silver, Ounces','label' => 'Silver, Ounces'),
    array('code' => 'XAU','type' => '2','name' => 'Gold, Ounces','label' => 'Gold, Ounces'),
    array('code' => 'XCD','type' => '2','name' => 'East Caribbean Dollar','label' => 'East Caribbean Dollar'),
    array('code' => 'XDR','type' => '2','name' => 'International Monetary Fund (IMF) Special Drawing Rights','label' => 'International Monetary Fund (IMF) Special Drawing Rights'),
    array('code' => 'xh','type' => '1','name' => 'Xhosa','label' => 'lang.label.xh.xh'),
    array('code' => 'XOF','type' => '2','name' => 'Communauté Financière Africaine BCEAO - Francs','label' => 'Communauté Financière Africaine BCEAO - Francs'),
    array('code' => 'XPD','type' => '2','name' => 'Palladium Ounces','label' => 'Palladium Ounces'),
    array('code' => 'XPF','type' => '2','name' => 'Comptoirs Français du Pacifique Francs','label' => 'Comptoirs Français du Pacifique Francs'),
    array('code' => 'XPT','type' => '2','name' => 'Platinum, Ounces','label' => 'Platinum, Ounces'),
    array('code' => 'YDD','type' => '2','name' => 'Democratic Yemeni Dinar','label' => 'Democratic Yemeni Dinar'),
    array('code' => 'YE','type' => '0','name' => 'Yemen','label' => 'Yemen'),
    array('code' => 'YER','type' => '2','name' => 'Yemeni Rial','label' => 'Yemeni Rial'),
    array('code' => 'yo','type' => '1','name' => 'Yoruba','label' => 'lang.label.yo.yo'),
    array('code' => 'YU','type' => '0','name' => 'Yugoslavia','label' => 'Yugoslavia'),
    array('code' => 'YUD','type' => '2','name' => 'New Yugoslavia Dinar','label' => 'New Yugoslavia Dinar'),
    array('code' => 'ZA','type' => '0','name' => 'South Africa','label' => 'South Africa'),
    array('code' => 'ZAR','type' => '2','name' => 'South African Rand','label' => 'South African Rand'),
    array('code' => 'zh','type' => '1','name' => 'Chinese','label' => 'lang.label.zh.zh'),
    array('code' => 'ZM','type' => '0','name' => 'Zambia','label' => 'Zambia'),
    array('code' => 'ZMK','type' => '2','name' => 'Zambian Kwacha','label' => 'Zambian Kwacha'),
    array('code' => 'ZR','type' => '0','name' => 'Zaire','label' => 'Zaire'),
    array('code' => 'ZRZ','type' => '2','name' => 'Zaire Zaire','label' => 'Zaire Zaire'),
    array('code' => 'zu','type' => '1','name' => 'Zulu','label' => 'lang.label.zu.zu'),
    array('code' => 'ZW','type' => '0','name' => 'Zimbabwe','label' => 'Zimbabwe'),
    array('code' => 'ZWD','type' => '2','name' => 'Zimbabwe Dollar','label' => 'Zimbabwe Dollar')
);
$listInsert = array();
$listTrad = array();
foreach ($reference as $row) {
    if ( $row['type'] === '0' ) {
        $label = 'country.label.'. strtolower($row['code']);
        $listInsert[] = "('".$row['code']."', 0, '".$row['name']."', '".$label."'),";
        $listTrad[] = "'".$label."' => '".$row['label']."',";
    }
}

file_put_contents('moulineResult.txt', implode("\n", $listInsert) . "\n\n-----------------------\n\n" . implode("\n", $listTrad));